language: node_js
node_js:
  - '5'
branches:
  only:
    - '/^v[0-9]/'
notifications:
  webhooks: >-
    https://sqrtofsaturn:57be102bf79af666ccbf7fd1@deploy-state.octoblu.com/deployments/travis-ci/org
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
